src/RssBundle/Entity/Feed.php
<?php

namespace RssBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Feed
 *
 * @ORM\Table(name="feeds", indexes={@ORM\Index(name="category_idx", columns={"category"})})
 * @ORM\Entity(repositoryClass="RssBundle\Entity\Repository\FeedRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Feed
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\OrderBy({"id"="desc"})
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    protected $url;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=45)
     */
    protected $title;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="last_update", type="datetime")
     */
    protected $lastUpdate;

    /**
     * @var string
     *
     * @ORM\Column(name="category", type="string", length=255)
     */
    protected $category;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Item", mappedBy="feed", cascade={"persist", "remove"}, fetch="EAGER"))
     * @ORM\OrderBy({"id"="DESC"})
     */
    protected $items;

    /**
     * @var Item
     */
    protected $lastItem;

    /**
     * Feed constructor.
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        /** @var Item $item */
        foreach ($this->getItems() as $item) {
            $item->setFeed($this);
        }
    }

    /**
     * @ORM\PostLoad
     */
    public function postLoad()
    {
        $item = $this->getItems()->first();
        $this->setLastItem($item);
    }

    /**
     * @return int
     */
    public function getItemsCount(): int
    {
        $items = $this->getItems();

        return $items->count();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Feed
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Feed
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set lastUpdate
     *
     * @param \DateTime $lastUpdate
     *
     * @return Feed
     */
    public function setLastUpdate($lastUpdate)
    {
        $this->lastUpdate = $lastUpdate;

        return $this;
    }

    /**
     * Get lastUpdate
     *
     * @return \DateTime
     */
    public function getLastUpdate()
    {
        return $this->lastUpdate;
    }

    /**
     * Set category
     *
     * @param string $category
     *
     * @return Feed
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Get Items
     *
     * @return Collection
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    /**
     * Set Items
     *
     * @param Collection $items
     */
    public function setItems(Collection $items)
    {
        $this->items = $items;
    }

    /**
     * @return Item
     */
    public function getLastItem(): Item
    {
        return $this->lastItem;
    }

    /**
     * @param Item $lastItem
     */
    public function setLastItem(Item $lastItem)
    {
        $this->lastItem = $lastItem;
    }


}

src/RssBundle/Resources/views/Rss/category.html.twig
{% extends "RssBundle:Template:base.html.twig" %}

{% block content %}
    {% include "RssBundle:Rss/Fragment:feedlist.html.twig" %}
{% endblock %}

src/RssBundle/Resources/views/Rss/index.html.twig
{% extends "RssBundle:Template:base.html.twig" %}

{% block content %}
    {% include "RssBundle:Rss/Fragment:feedlist.html.twig" %}
{% endblock %}

src/RssBundle/Resources/views/Rss/show.html.twig
{% extends "RssBundle:Template:base.html.twig" %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ feed.title }}</h4>
            <h6 class="card-subtitle text-muted">{{ feed.lastUpdate|date('Y-m-d H:i:s') }}</h6>
            <div class="card-text">
                <div><strong>Category: </strong> {{ feed.category }}</div>
                <div><strong>Url: </strong>{{ feed.url }}</div>
                <div><strong>Items: </strong>{{ feed.itemsCount }}</div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Published</th>
            <th>Title</th>
            <th>Description</th>
            <th>Link</th>
        </tr>
        </thead>
        <tbody>
        {% for item in feed.items %}
            <tr>
                <td>{{ item.published|date('Y-m-d H:i:s') }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description|raw }}</td>
                <td><a href="{{ item.link }}">{{ item.link }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}